#include "test_atom_basic_common.h"

int test_amplitude_multiply(void);
int test_soft_clip_bounds_and_monotonicity(void);
int test_delay_line_impulse_position(void);
int test_biquad_impulse_stability(void);
int test_biquad_cutoff_smoothing(void);
int test_biquad_modes_are_finite(void);
int test_process_info_frame_limits(void);
int test_process_info_modulation_frame_limits(void);
int test_process_info_control_frame_limits(void);
int test_process_info_delay_frame_limits(void);
int test_process_info_arithmetic_mix_frame_limits(void);
int test_process_info_amplitude_state_frame_limits(void);
int test_process_info_generator_frame_limits(void);
int test_process_info_modulation_remaining_frame_limits(void);
int test_process_info_remaining_detector_frame_limits(void);
int test_process_info_remaining_filter_frame_limits(void);
int test_process_info_remaining_mix_nonlinear_frame_limits(void);
int test_process_info_remaining_interpolation_src_frame_limits(void);
int test_process_info_remaining_spectral_frame_limits(void);
int test_process_info_downsample_frame_limits(void);
int test_process_info_remaining_overlap_frame_limits(void);
int test_process_info_freq_shift_frame_limits(void);

int main(void) {
    if (test_amplitude_multiply())
        return 1;
    if (test_soft_clip_bounds_and_monotonicity())
        return 1;
    if (test_delay_line_impulse_position())
        return 1;
    if (test_biquad_impulse_stability())
        return 1;
    if (test_biquad_cutoff_smoothing())
        return 1;
    if (test_biquad_modes_are_finite())
        return 1;
    if (test_process_info_frame_limits())
        return 1;
    if (test_process_info_modulation_frame_limits())
        return 1;
    if (test_process_info_control_frame_limits())
        return 1;
    if (test_process_info_delay_frame_limits())
        return 1;
    if (test_process_info_arithmetic_mix_frame_limits())
        return 1;
    if (test_process_info_amplitude_state_frame_limits())
        return 1;
    if (test_process_info_generator_frame_limits())
        return 1;
    if (test_process_info_modulation_remaining_frame_limits())
        return 1;
    if (test_process_info_remaining_detector_frame_limits())
        return 1;
    if (test_process_info_remaining_filter_frame_limits())
        return 1;
    if (test_process_info_remaining_mix_nonlinear_frame_limits())
        return 1;
    if (test_process_info_remaining_interpolation_src_frame_limits())
        return 1;
    if (test_process_info_remaining_spectral_frame_limits())
        return 1;
    if (test_process_info_downsample_frame_limits())
        return 1;
    if (test_process_info_remaining_overlap_frame_limits())
        return 1;
    if (test_process_info_freq_shift_frame_limits())
        return 1;
    return 0;
}
