// Generated from schema/atoms/atoms.json by tools/generate_atom_artifacts.pl. Do not edit.

export type FieldDef = { name: string; type: 'float' | 'int' | 'enum' | 'buffer' | 'float_matrix'; required: boolean; options?: string[] };

export type AtomDef = {
  name: string;
  category: 'generation' | 'amplitude' | 'delay' | 'filter' | 'detect' | 'modulation' | 'interpolation' | 'src' | 'freq' | 'mix' | 'nonlinear';
  dispatch: 'process' | 'fft' | 'ifft' | 'multiply' | 'window' | 'overlap_add' | 'overlap_save' | 'stream';
  ins: string[];
  outs: string[];
  config: FieldDef[];
};

export const ATOM_CATALOG: AtomDef[] = [
  {
    name: 'amplitude_accumulate',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'amplitude_latch',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal', 'gate'],
    outs: ['signal'],
    config: [{ name: 'threshold', type: 'float', required: true }],
  },
  {
    name: 'amplitude_add',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal_a', 'signal_b'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'amplitude_clip_hard',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'threshold', type: 'float', required: true }],
  },
  {
    name: 'amplitude_clip_soft',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'threshold', type: 'float', required: true }, { name: 'curve', type: 'int', required: true }],
  },
  {
    name: 'amplitude_divide',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['numerator', 'denominator'],
    outs: ['signal'],
    config: [{ name: 'epsilon', type: 'float', required: true }],
  },
  {
    name: 'amplitude_multiply',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal_a', 'signal_b'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'amplitude_normalize',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'target_level', type: 'float', required: true }, { name: 'mode', type: 'int', required: true }],
  },
  {
    name: 'amplitude_smooth',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'attack', type: 'float', required: true }, { name: 'release', type: 'float', required: true }],
  },
  {
    name: 'amplitude_subtract',
    category: 'amplitude',
    dispatch: 'process',
    ins: ['signal_a', 'signal_b'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'delay_fractional',
    category: 'delay',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'delay_samples', type: 'float', required: true }, { name: 'interpolation', type: 'int', required: true }],
  },
  {
    name: 'delay_line',
    category: 'delay',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'length', type: 'int', required: true }],
  },
  {
    name: 'delay_tap_feedback',
    category: 'delay',
    dispatch: 'process',
    ins: ['buffer', 'tap_position'],
    outs: ['signal'],
    config: [{ name: 'coefficient', type: 'float', required: true }],
  },
  {
    name: 'delay_tap_feedforward',
    category: 'delay',
    dispatch: 'process',
    ins: ['buffer', 'tap_position'],
    outs: ['signal'],
    config: [{ name: 'coefficient', type: 'float', required: true }],
  },
  {
    name: 'delay_unit',
    category: 'delay',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'detect_autocorrelate',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['correlation'],
    config: [{ name: 'max_lag', type: 'int', required: true }],
  },
  {
    name: 'detect_pitch',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['pitch'],
    config: [{ name: 'max_lag', type: 'int', required: true }],
  },
  {
    name: 'detect_envelope',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['envelope'],
    config: [{ name: 'attack', type: 'float', required: true }, { name: 'release', type: 'float', required: true }],
  },
  {
    name: 'detect_peak',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['level'],
    config: [{ name: 'attack', type: 'float', required: true }, { name: 'release', type: 'float', required: true }],
  },
  {
    name: 'detect_rms',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['level'],
    config: [{ name: 'window_size', type: 'int', required: true }],
  },
  {
    name: 'detect_slope',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['slope'],
    config: [],
  },
  {
    name: 'detect_threshold',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['gate'],
    config: [{ name: 'threshold', type: 'float', required: true }],
  },
  {
    name: 'detect_zero_crossing',
    category: 'detect',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['trigger'],
    config: [],
  },
  {
    name: 'filter_allpass',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'delay_samples', type: 'int', required: true }, { name: 'coefficient', type: 'float', required: true }],
  },
  {
    name: 'filter_biquad_coefficients',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'b0', type: 'float', required: true }, { name: 'b1', type: 'float', required: true }, { name: 'b2', type: 'float', required: true }, { name: 'a1', type: 'float', required: true }, { name: 'a2', type: 'float', required: true }],
  },
  {
    name: 'filter_biquad',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal', 'cutoff'],
    outs: ['signal'],
    config: [{ name: 'cutoff', type: 'float', required: true }, { name: 'q', type: 'float', required: true }, { name: 'mode', type: 'int', required: true }, { name: 'smoothing_ms', type: 'float', required: true }],
  },
  {
    name: 'filter_comb_fb',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal', 'delay'],
    outs: ['signal'],
    config: [{ name: 'delay_samples', type: 'int', required: true }, { name: 'coefficient', type: 'float', required: true }],
  },
  {
    name: 'filter_comb_ff',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'delay_samples', type: 'int', required: true }, { name: 'coefficient', type: 'float', required: true }],
  },
  {
    name: 'filter_dc_block',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'coefficient', type: 'float', required: true }],
  },
  {
    name: 'filter_differentiate',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'filter_fir',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'kernel', type: 'buffer', required: true }, { name: 'kernel_size', type: 'int', required: true }],
  },
  {
    name: 'filter_integrate',
    category: 'filter',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'freq_fft',
    category: 'freq',
    dispatch: 'fft',
    ins: ['signal'],
    outs: ['real', 'imag'],
    config: [{ name: 'block_size', type: 'int', required: true }],
  },
  {
    name: 'freq_ifft',
    category: 'freq',
    dispatch: 'ifft',
    ins: ['real', 'imag'],
    outs: ['signal'],
    config: [{ name: 'block_size', type: 'int', required: true }],
  },
  {
    name: 'freq_multiply',
    category: 'freq',
    dispatch: 'multiply',
    ins: ['real_a', 'imag_a', 'real_b', 'imag_b'],
    outs: ['real', 'imag'],
    config: [{ name: 'block_size', type: 'int', required: true }],
  },
  {
    name: 'freq_overlap_add',
    category: 'freq',
    dispatch: 'overlap_add',
    ins: ['frame'],
    outs: ['signal'],
    config: [{ name: 'block_size', type: 'int', required: true }, { name: 'hop_size', type: 'int', required: true }],
  },
  {
    name: 'freq_overlap_save',
    category: 'freq',
    dispatch: 'overlap_save',
    ins: ['signal'],
    outs: ['frame'],
    config: [{ name: 'block_size', type: 'int', required: true }, { name: 'hop_size', type: 'int', required: true }],
  },
  {
    name: 'freq_window',
    category: 'freq',
    dispatch: 'window',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'window_type', type: 'int', required: true }, { name: 'block_size', type: 'int', required: true }],
  },
  {
    name: 'freq_shift',
    category: 'freq',
    dispatch: 'process',
    ins: ['signal', 'pitch_shift'],
    outs: ['signal'],
    config: [{ name: 'block_size', type: 'int', required: true }],
  },
  {
    name: 'generation_dc',
    category: 'generation',
    dispatch: 'process',
    ins: [],
    outs: ['signal'],
    config: [{ name: 'value', type: 'float', required: true }],
  },
  {
    name: 'generation_envelope',
    category: 'generation',
    dispatch: 'process',
    ins: ['gate'],
    outs: ['signal'],
    config: [{ name: 'attack', type: 'float', required: true }, { name: 'decay', type: 'float', required: true }, { name: 'sustain', type: 'float', required: true }, { name: 'release', type: 'float', required: true }],
  },
  {
    name: 'generation_impulse',
    category: 'generation',
    dispatch: 'process',
    ins: [],
    outs: ['signal'],
    config: [{ name: 'interval', type: 'float', required: true }],
  },
  {
    name: 'generation_lfo',
    category: 'generation',
    dispatch: 'process',
    ins: [],
    outs: ['signal'],
    config: [{ name: 'frequency', type: 'float', required: true }, { name: 'waveform', type: 'int', required: true }, { name: 'phase_offset', type: 'float', required: true }],
  },
  {
    name: 'generation_noise',
    category: 'generation',
    dispatch: 'process',
    ins: [],
    outs: ['signal'],
    config: [{ name: 'amplitude', type: 'float', required: true }, { name: 'color', type: 'int', required: true }],
  },
  {
    name: 'generation_oscillator',
    category: 'generation',
    dispatch: 'process',
    ins: ['frequency'],
    outs: ['signal'],
    config: [{ name: 'frequency', type: 'float', required: true }, { name: 'waveform', type: 'int', required: true }, { name: 'phase_offset', type: 'float', required: true }],
  },
  {
    name: 'interpolation_cubic',
    category: 'interpolation',
    dispatch: 'process',
    ins: ['signal_n1', 'signal_a', 'signal_b', 'signal_c', 't'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'interpolation_lagrange',
    category: 'interpolation',
    dispatch: 'process',
    ins: ['samples', 't'],
    outs: ['signal'],
    config: [{ name: 'order', type: 'int', required: true }],
  },
  {
    name: 'interpolation_linear',
    category: 'interpolation',
    dispatch: 'process',
    ins: ['signal_a', 'signal_b', 't'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'interpolation_sinc',
    category: 'interpolation',
    dispatch: 'process',
    ins: ['buffer', 'position'],
    outs: ['signal'],
    config: [{ name: 'num_taps', type: 'int', required: true }],
  },
  {
    name: 'mix_crossfade',
    category: 'mix',
    dispatch: 'process',
    ins: ['signal_a', 'signal_b'],
    outs: ['signal'],
    config: [{ name: 't', type: 'float', required: true }],
  },
  {
    name: 'mix_decode_ms',
    category: 'mix',
    dispatch: 'process',
    ins: ['mid', 'side'],
    outs: ['left', 'right'],
    config: [],
  },
  {
    name: 'mix_encode_ms',
    category: 'mix',
    dispatch: 'process',
    ins: ['left', 'right'],
    outs: ['mid', 'side'],
    config: [],
  },
  {
    name: 'mix_matrix',
    category: 'mix',
    dispatch: 'process',
    ins: ['signals'],
    outs: ['signals'],
    config: [{ name: 'coefficients', type: 'float_matrix', required: true }],
  },
  {
    name: 'mix_pan_stereo',
    category: 'mix',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['left', 'right'],
    config: [{ name: 'position', type: 'float', required: true }],
  },
  {
    name: 'mix_wet_dry',
    category: 'mix',
    dispatch: 'process',
    ins: ['dry', 'wet'],
    outs: ['signal'],
    config: [{ name: 'mix', type: 'float', required: true }],
  },
  {
    name: 'modulation_amplitude',
    category: 'modulation',
    dispatch: 'process',
    ins: ['signal', 'modulator'],
    outs: ['signal'],
    config: [{ name: 'depth', type: 'float', required: true }],
  },
  {
    name: 'modulation_frequency',
    category: 'modulation',
    dispatch: 'process',
    ins: ['signal', 'modulator'],
    outs: ['signal'],
    config: [{ name: 'depth', type: 'float', required: true }],
  },
  {
    name: 'modulation_phase',
    category: 'modulation',
    dispatch: 'process',
    ins: ['signal', 'modulator'],
    outs: ['signal'],
    config: [{ name: 'depth', type: 'float', required: true }],
  },
  {
    name: 'modulation_ring',
    category: 'modulation',
    dispatch: 'process',
    ins: ['signal', 'modulator'],
    outs: ['signal'],
    config: [],
  },
  {
    name: 'modulation_scrub',
    category: 'modulation',
    dispatch: 'process',
    ins: ['buffer', 'position'],
    outs: ['signal'],
    config: [{ name: 'buffer_size', type: 'int', required: true }],
  },
  {
    name: 'nonlinear_bitcrush',
    category: 'nonlinear',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'bit_depth', type: 'float', required: true }],
  },
  {
    name: 'nonlinear_sample_hold',
    category: 'nonlinear',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'factor', type: 'float', required: true }],
  },
  {
    name: 'nonlinear_waveshape',
    category: 'nonlinear',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'transfer_table', type: 'buffer', required: true }, { name: 'table_size', type: 'int', required: true }],
  },
  {
    name: 'src_antialias',
    category: 'src',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'cutoff', type: 'float', required: true }],
  },
  {
    name: 'src_antiimage',
    category: 'src',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'cutoff', type: 'float', required: true }],
  },
  {
    name: 'src_convert_format',
    category: 'src',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'from_format', type: 'int', required: true }, { name: 'to_format', type: 'int', required: true }],
  },
  {
    name: 'src_downsample',
    category: 'src',
    dispatch: 'stream',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'factor', type: 'int', required: true }],
  },
  {
    name: 'src_upsample',
    category: 'src',
    dispatch: 'stream',
    ins: ['signal'],
    outs: ['signal'],
    config: [{ name: 'factor', type: 'int', required: true }],
  },
  {
    name: 'freq_quantize',
    category: 'freq',
    dispatch: 'process',
    ins: ['signal'],
    outs: ['signal'],
    config: [],
  },
];

export const ATOM_MAP = new Map<string, AtomDef>(ATOM_CATALOG.map(atom => [atom.name, atom]));
