#!/usr/bin/env perl

use strict;
use warnings;

use File::Basename qw(dirname);
use File::Path qw(make_path);

sub usage {
    die "usage: $0 OUTPUT_C TYPE_HEADER [TYPE_HEADER ...]\n";
}

my $output_path = shift @ARGV // usage();
@ARGV or usage();

my %profiles;
my @atoms;

for my $path (@ARGV) {
    open my $input, '<', $path or die "cannot read $path: $!\n";

    while (my $line = <$input>) {
        if ($line =~ /^#define\s+APG_IO_FIELDS_([A-Z0-9_]+)\s+\{\s*(.*?)\s*\}/) {
            $profiles{$1} = $2;
            next;
        }

        if ($line =~ /^\s*X\(\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*\{(.*)\},\s*\{(.*)\}\)\s*\\?\s*$/) {
            push @atoms,
                {
                name        => trim($1),
                out_profile => trim($2),
                in_profile  => trim($3),
                params      => trim($4),
                state       => trim($5),
                };
        }
    }

    close $input or die "cannot close $path: $!\n";
}

@atoms or die "no APG DSP type rows found in input headers\n";

for my $atom (@atoms) {
    for my $key (qw(out_profile in_profile)) {
        my $profile = $atom->{$key};
        exists $profiles{$profile} or die "unknown I/O profile $profile for $atom->{name}\n";
    }
}

@atoms = sort { $a->{name} cmp $b->{name} } @atoms;

my $output_dir = dirname($output_path);
make_path($output_dir) unless -d $output_dir;
open my $output, '>', $output_path or die "cannot write $output_path: $!\n";

print {$output} <<'HEADER';
/* Generated by codegen/generate_dsp_types_abi_snapshot.pl. */
#include <atom/dsp_types.h>

#include <stddef.h>
#include <stdio.h>

#define SNAPSHOT_ENUM(stream, enumerator) fprintf((stream), "enum,%s,,,,,%d\n", #enumerator, (int)(enumerator))
#define SNAPSHOT_TYPE(stream, type)       fprintf((stream), "type,%s,%zu,%zu,,,\n", #type, sizeof(type), _Alignof(type))
#define SNAPSHOT_FIELD(stream, type, field) \
    fprintf((stream), "field,%s,,,%s,%zu,\n", #type, #field, offsetof(type, field))

static FILE *open_output(int argc, char **argv) {
    if (argc == 1)
        return stdout;
    if (argc != 2)
        return NULL;
    return fopen(argv[1], "wb");
}

int main(int argc, char **argv) {
    FILE *output = open_output(argc, argv);
    if (!output) {
        fprintf(stderr, "usage: %s [OUTPUT_CSV]\n", argv[0]);
        return 2;
    }

    fputs("record,name,size,align,field,offset,value\n", output);

    SNAPSHOT_ENUM(output, WAVEFORM_SINE);
    SNAPSHOT_ENUM(output, WAVEFORM_SAW);
    SNAPSHOT_ENUM(output, WAVEFORM_SQUARE);
    SNAPSHOT_ENUM(output, WAVEFORM_TRIANGLE);
    SNAPSHOT_ENUM(output, WAVEFORM_NOISE_WHITE);
    SNAPSHOT_ENUM(output, WAVEFORM_NOISE_PINK);
    SNAPSHOT_ENUM(output, WAVEFORM_NOISE_BROWN);
    SNAPSHOT_ENUM(output, NORMALIZE_PEAK);
    SNAPSHOT_ENUM(output, NORMALIZE_RMS);
    SNAPSHOT_ENUM(output, INTERPOLATION_LINEAR);
    SNAPSHOT_ENUM(output, INTERPOLATION_CUBIC);
    SNAPSHOT_ENUM(output, INTERPOLATION_SINC);
    SNAPSHOT_ENUM(output, INTERPOLATION_LAGRANGE);
    SNAPSHOT_ENUM(output, WINDOW_HANN);
    SNAPSHOT_ENUM(output, WINDOW_HAMMING);
    SNAPSHOT_ENUM(output, WINDOW_BLACKMAN);
    SNAPSHOT_ENUM(output, WINDOW_RECTANGULAR);

    SNAPSHOT_TYPE(output, apg_buffer_t);
    SNAPSHOT_FIELD(output, apg_buffer_t, data);
    SNAPSHOT_FIELD(output, apg_buffer_t, capacity);

    SNAPSHOT_TYPE(output, apg_const_buffer_t);
    SNAPSHOT_FIELD(output, apg_const_buffer_t, data);
    SNAPSHOT_FIELD(output, apg_const_buffer_t, length);

    SNAPSHOT_TYPE(output, Signal);
    SNAPSHOT_FIELD(output, Signal, data);
    SNAPSHOT_FIELD(output, Signal, capacity);

    SNAPSHOT_TYPE(output, Spectrum);
    SNAPSHOT_FIELD(output, Spectrum, data);
    SNAPSHOT_FIELD(output, Spectrum, capacity);

    SNAPSHOT_TYPE(output, Buffer);
    SNAPSHOT_FIELD(output, Buffer, data);
    SNAPSHOT_FIELD(output, Buffer, capacity);

    SNAPSHOT_TYPE(output, atom_mono_t);
    SNAPSHOT_FIELD(output, atom_mono_t, signal);

    SNAPSHOT_TYPE(output, atom_pair_t);
    SNAPSHOT_FIELD(output, atom_pair_t, signal_a);
    SNAPSHOT_FIELD(output, atom_pair_t, signal_b);

    SNAPSHOT_TYPE(output, atom_stereo_t);
    SNAPSHOT_FIELD(output, atom_stereo_t, left);
    SNAPSHOT_FIELD(output, atom_stereo_t, right);

    SNAPSHOT_TYPE(output, atom_complex_t);
    SNAPSHOT_FIELD(output, atom_complex_t, real);
    SNAPSHOT_FIELD(output, atom_complex_t, imag);

    SNAPSHOT_TYPE(output, atom_ms_t);
    SNAPSHOT_FIELD(output, atom_ms_t, mid);
    SNAPSHOT_FIELD(output, atom_ms_t, side);

    SNAPSHOT_TYPE(output, atom_wet_dry_t);
    SNAPSHOT_FIELD(output, atom_wet_dry_t, dry);
    SNAPSHOT_FIELD(output, atom_wet_dry_t, wet);

    SNAPSHOT_TYPE(output, atom_div_t);
    SNAPSHOT_FIELD(output, atom_div_t, numerator);
    SNAPSHOT_FIELD(output, atom_div_t, denominator);
HEADER

for my $atom (@atoms) {
    emit_layout($output, "$atom->{name}_out_t", $profiles{$atom->{out_profile}});
    emit_layout($output, "$atom->{name}_in_t", $profiles{$atom->{in_profile}});
    emit_layout($output, "$atom->{name}_params_t", $atom->{params});
    emit_layout($output, "$atom->{name}_state_t", $atom->{state});
}

print {$output} <<'FOOTER';

    if (output != stdout && fclose(output) != 0)
        return 1;
    return 0;
}

#undef SNAPSHOT_FIELD
#undef SNAPSHOT_TYPE
#undef SNAPSHOT_ENUM
FOOTER

close $output or die "cannot close $output_path: $!\n";

sub trim {
    my ($value) = @_;
    $value =~ s/^\s+//;
    $value =~ s/\s+$//;
    return $value;
}

sub emit_layout {
    my ($stream, $type, $fields) = @_;
    print {$stream} "\n    SNAPSHOT_TYPE(output, $type);\n";

    for my $declaration (split /;/, $fields) {
        $declaration = trim($declaration);
        next if $declaration eq '';
        $declaration =~ /([A-Za-z_][A-Za-z0-9_]*)$/
            or die "cannot identify field in '$declaration' for $type\n";
        print {$stream} "    SNAPSHOT_FIELD(output, $type, $1);\n";
    }
}
