// Generated from schema/atoms/atoms.json by tools/generate_atom_artifacts.pl. Do not edit.

export type AtomVisibility = 'public' | 'advanced' | 'internal';
export type ParameterValue = number | boolean | string | number[] | number[][];

export type FieldDef = {
  name: string;
  type: 'float' | 'int' | 'bool' | 'enum' | 'buffer' | 'float_matrix';
  required: boolean;
  default: ParameterValue;
  min?: number;
  max?: number;
  unit?: 'hz' | 'ms' | 'db' | 'ratio' | 'samples';
  scale?: 'linear' | 'logarithmic';
  realtime: boolean;
  smoothingMs?: number;
  structural: boolean;
  options?: string[];
  optionValues?: number[];
};

export type AtomDef = {
  name: string;
  category: 'generation' | 'amplitude' | 'delay' | 'filter' | 'detect' | 'modulation' | 'interpolation' | 'src' | 'freq' | 'mix' | 'nonlinear' | 'math';
  visibility: AtomVisibility;
  dispatch: 'process' | 'fft' | 'ifft' | 'multiply' | 'window' | 'overlap_add' | 'overlap_save' | 'stream';
  ins: string[];
  outs: string[];
  config: FieldDef[];
};

export const ATOM_CATALOG: AtomDef[] = [
  {
    name: 'amplitude_accumulate',
    category: 'amplitude',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'amplitude_latch',
    category: 'amplitude',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal", "gate"],
    outs: ["signal"],
    config: [{ name: "threshold", type: "float", required: true, default: 0.5, min: -1, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'amplitude_add',
    category: 'amplitude',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal_a", "signal_b"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'amplitude_clip_hard',
    category: 'amplitude',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "threshold", type: "float", required: true, default: 1, min: 0.001, max: 4, unit: "ratio", scale: "logarithmic", realtime: true, structural: false }],
  },
  {
    name: 'amplitude_clip_soft',
    category: 'amplitude',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "threshold", type: "float", required: true, default: 1, min: 0.001, max: 4, unit: "ratio", scale: "logarithmic", realtime: true, structural: false }, { name: "curve", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["cubic","tanh"], optionValues: [0,1] }],
  },
  {
    name: 'amplitude_divide',
    category: 'amplitude',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["numerator", "denominator"],
    outs: ["signal"],
    config: [{ name: "epsilon", type: "float", required: true, default: 1e-06, min: 1e-12, max: 0.1, scale: "logarithmic", realtime: true, structural: false }],
  },
  {
    name: 'amplitude_multiply',
    category: 'amplitude',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal_a", "signal_b"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'amplitude_normalize',
    category: 'amplitude',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "target_level", type: "float", required: true, default: 1, min: 0.001, max: 1, unit: "ratio", scale: "logarithmic", realtime: true, structural: false }, { name: "mode", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["peak","rms"], optionValues: [0,1] }],
  },
  {
    name: 'amplitude_smooth',
    category: 'amplitude',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "attack", type: "float", required: true, default: 0.01, min: 0, max: 60, realtime: true, structural: false }, { name: "release", type: "float", required: true, default: 0.1, min: 0, max: 60, realtime: true, structural: false }],
  },
  {
    name: 'amplitude_subtract',
    category: 'amplitude',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal_a", "signal_b"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'delay_fractional',
    category: 'delay',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "delay_samples", type: "float", required: true, default: 1, min: 0, max: 191999, unit: "samples", realtime: true, structural: false }, { name: "interpolation", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["linear","cubic","sinc","lagrange"], optionValues: [0,1,2,3] }],
  },
  {
    name: 'delay_line',
    category: 'delay',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "length", type: "int", required: true, default: 1, min: 1, max: 192000, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'delay_tap_feedback',
    category: 'delay',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["buffer", "tap_position"],
    outs: ["signal"],
    config: [{ name: "coefficient", type: "float", required: true, default: 0.5, min: -1, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'delay_tap_feedforward',
    category: 'delay',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["buffer", "tap_position"],
    outs: ["signal"],
    config: [{ name: "coefficient", type: "float", required: true, default: 0.5, min: -1, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'delay_unit',
    category: 'delay',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'detect_autocorrelate',
    category: 'detect',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["correlation"],
    config: [{ name: "max_lag", type: "int", required: true, default: 512, min: 1, max: 1024, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'detect_pitch',
    category: 'detect',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["pitch"],
    config: [{ name: "max_lag", type: "int", required: true, default: 512, min: 33, max: 1024, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'detect_envelope',
    category: 'detect',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["envelope"],
    config: [{ name: "attack", type: "float", required: true, default: 0.01, min: 0, max: 60, realtime: true, structural: false }, { name: "release", type: "float", required: true, default: 0.1, min: 0, max: 60, realtime: true, structural: false }],
  },
  {
    name: 'detect_peak',
    category: 'detect',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["level"],
    config: [{ name: "attack", type: "float", required: true, default: 0.01, min: 0, max: 60, realtime: true, structural: false }, { name: "release", type: "float", required: true, default: 0.1, min: 0, max: 60, realtime: true, structural: false }],
  },
  {
    name: 'detect_rms',
    category: 'detect',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["level"],
    config: [{ name: "window_size", type: "int", required: true, default: 256, min: 1, max: 4096, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'detect_slope',
    category: 'detect',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["slope"],
    config: [],
  },
  {
    name: 'detect_threshold',
    category: 'detect',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["gate"],
    config: [{ name: "threshold", type: "float", required: true, default: 0.5, min: -1, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'detect_zero_crossing',
    category: 'detect',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["trigger"],
    config: [],
  },
  {
    name: 'filter_allpass',
    category: 'filter',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "delay_samples", type: "int", required: true, default: 1, min: 1, max: 47999, unit: "samples", realtime: false, structural: true }, { name: "coefficient", type: "float", required: true, default: 0.5, min: -0.999, max: 0.999, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'filter_biquad_coefficients',
    category: 'filter',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "b0", type: "float", required: true, default: 1, min: -4, max: 4, unit: "ratio", realtime: true, structural: false }, { name: "b1", type: "float", required: true, default: 0, min: -4, max: 4, unit: "ratio", realtime: true, structural: false }, { name: "b2", type: "float", required: true, default: 0, min: -4, max: 4, unit: "ratio", realtime: true, structural: false }, { name: "a1", type: "float", required: true, default: 0, min: -2, max: 2, unit: "ratio", realtime: true, structural: false }, { name: "a2", type: "float", required: true, default: 0, min: -2, max: 2, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'filter_biquad',
    category: 'filter',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal", "cutoff"],
    outs: ["signal"],
    config: [{ name: "cutoff", type: "float", required: true, default: 1000, min: 20, max: 20000, unit: "hz", scale: "logarithmic", realtime: true, smoothingMs: 10, structural: false }, { name: "q", type: "float", required: true, default: 0.707, min: 0.05, max: 20, unit: "ratio", scale: "logarithmic", realtime: true, smoothingMs: 10, structural: false }, { name: "mode", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["lowpass","highpass","bandpass","notch"], optionValues: [0,1,2,3] }, { name: "smoothing_ms", type: "float", required: true, default: 10, min: 0, max: 1000, unit: "ms", realtime: true, structural: false }],
  },
  {
    name: 'filter_comb_fb',
    category: 'filter',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal", "delay"],
    outs: ["signal"],
    config: [{ name: "delay_samples", type: "int", required: true, default: 1, min: 1, max: 47999, unit: "samples", realtime: false, structural: true }, { name: "coefficient", type: "float", required: true, default: 0.5, min: -0.999, max: 0.999, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'filter_comb_ff',
    category: 'filter',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "delay_samples", type: "int", required: true, default: 1, min: 1, max: 47999, unit: "samples", realtime: false, structural: true }, { name: "coefficient", type: "float", required: true, default: 0.5, min: -4, max: 4, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'filter_dc_block',
    category: 'filter',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "coefficient", type: "float", required: true, default: 0.995, min: 0.9, max: 0.99999, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'filter_differentiate',
    category: 'filter',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'filter_fir',
    category: 'filter',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "kernel", type: "buffer", required: true, default: "", realtime: false, structural: true }, { name: "kernel_size", type: "int", required: true, default: 0, min: 0, max: 1024, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'filter_integrate',
    category: 'filter',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'freq_fft',
    category: 'freq',
    visibility: 'advanced',
    dispatch: 'fft',
    ins: ["signal"],
    outs: ["real", "imag"],
    config: [{ name: "block_size", type: "int", required: true, default: 512, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'freq_ifft',
    category: 'freq',
    visibility: 'advanced',
    dispatch: 'ifft',
    ins: ["real", "imag"],
    outs: ["signal"],
    config: [{ name: "block_size", type: "int", required: true, default: 512, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'freq_multiply',
    category: 'freq',
    visibility: 'advanced',
    dispatch: 'multiply',
    ins: ["real_a", "imag_a", "real_b", "imag_b"],
    outs: ["real", "imag"],
    config: [{ name: "block_size", type: "int", required: true, default: 512, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'freq_overlap_add',
    category: 'freq',
    visibility: 'internal',
    dispatch: 'overlap_add',
    ins: ["frame"],
    outs: ["signal"],
    config: [{ name: "block_size", type: "int", required: true, default: 512, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }, { name: "hop_size", type: "int", required: true, default: 256, min: 1, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'freq_overlap_save',
    category: 'freq',
    visibility: 'internal',
    dispatch: 'overlap_save',
    ins: ["signal"],
    outs: ["frame"],
    config: [{ name: "block_size", type: "int", required: true, default: 512, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }, { name: "hop_size", type: "int", required: true, default: 256, min: 1, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'freq_window',
    category: 'freq',
    visibility: 'internal',
    dispatch: 'window',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "window_type", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["hann","hamming","blackman","rectangular"], optionValues: [0,1,2,3] }, { name: "block_size", type: "int", required: true, default: 512, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'freq_shift',
    category: 'freq',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal", "pitch_shift"],
    outs: ["signal"],
    config: [{ name: "block_size", type: "int", required: true, default: 1024, min: 2, max: 16384, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'generation_dc',
    category: 'generation',
    visibility: 'public',
    dispatch: 'process',
    ins: [],
    outs: ["signal"],
    config: [{ name: "value", type: "float", required: true, default: 0, min: -4, max: 4, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'generation_envelope',
    category: 'generation',
    visibility: 'public',
    dispatch: 'process',
    ins: ["gate"],
    outs: ["signal"],
    config: [{ name: "attack", type: "float", required: true, default: 0.01, min: 0, max: 60, realtime: true, structural: false }, { name: "decay", type: "float", required: true, default: 0.1, min: 0, max: 60, realtime: true, structural: false }, { name: "sustain", type: "float", required: true, default: 0.7, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }, { name: "release", type: "float", required: true, default: 0.2, min: 0, max: 60, realtime: true, structural: false }],
  },
  {
    name: 'generation_impulse',
    category: 'generation',
    visibility: 'public',
    dispatch: 'process',
    ins: [],
    outs: ["signal"],
    config: [{ name: "interval", type: "float", required: true, default: 1, min: 0, max: 3600, realtime: true, structural: false }],
  },
  {
    name: 'generation_lfo',
    category: 'generation',
    visibility: 'internal',
    dispatch: 'process',
    ins: [],
    outs: ["signal"],
    config: [{ name: "frequency", type: "float", required: true, default: 1, min: 0.001, max: 20, unit: "hz", scale: "logarithmic", realtime: true, structural: false }, { name: "waveform", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["sine","saw","square","triangle"], optionValues: [0,1,2,3] }, { name: "phase_offset", type: "float", required: true, default: 0, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'generation_noise',
    category: 'generation',
    visibility: 'public',
    dispatch: 'process',
    ins: [],
    outs: ["signal"],
    config: [{ name: "amplitude", type: "float", required: true, default: 0.2, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }, { name: "color", type: "enum", required: true, default: 4, realtime: true, structural: false, options: ["white","pink","brown"], optionValues: [4,5,6] }],
  },
  {
    name: 'generation_oscillator',
    category: 'generation',
    visibility: 'public',
    dispatch: 'process',
    ins: ["frequency"],
    outs: ["signal"],
    config: [{ name: "frequency", type: "float", required: true, default: 440, min: 0.01, max: 20000, unit: "hz", scale: "logarithmic", realtime: true, structural: false }, { name: "waveform", type: "enum", required: true, default: 0, realtime: true, structural: false, options: ["sine","saw","square","triangle"], optionValues: [0,1,2,3] }, { name: "phase_offset", type: "float", required: true, default: 0, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'interpolation_cubic',
    category: 'interpolation',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal_n1", "signal_a", "signal_b", "signal_c", "t"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'interpolation_lagrange',
    category: 'interpolation',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["samples", "t"],
    outs: ["signal"],
    config: [{ name: "order", type: "int", required: true, default: 3, min: 1, max: 16, realtime: false, structural: true }],
  },
  {
    name: 'interpolation_linear',
    category: 'interpolation',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal_a", "signal_b", "t"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'interpolation_sinc',
    category: 'interpolation',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["buffer", "position"],
    outs: ["signal"],
    config: [{ name: "num_taps", type: "int", required: true, default: 32, min: 2, max: 128, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'mix_crossfade',
    category: 'mix',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal_a", "signal_b"],
    outs: ["signal"],
    config: [{ name: "t", type: "float", required: true, default: 0.5, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }, { name: "curve", type: "enum", required: false, default: 0, realtime: true, structural: false, options: ["linear","equal_power"], optionValues: [0,1] }],
  },
  {
    name: 'mix_decode_ms',
    category: 'mix',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["mid", "side"],
    outs: ["left", "right"],
    config: [],
  },
  {
    name: 'mix_encode_ms',
    category: 'mix',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["left", "right"],
    outs: ["mid", "side"],
    config: [],
  },
  {
    name: 'mix_matrix',
    category: 'mix',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signals"],
    outs: ["signals"],
    config: [{ name: "coefficients", type: "float_matrix", required: true, default: [[1]], realtime: false, structural: true }],
  },
  {
    name: 'mix_pan_stereo',
    category: 'mix',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["left", "right"],
    config: [{ name: "position", type: "float", required: true, default: 0, min: -1, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'mix_wet_dry',
    category: 'mix',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["dry", "wet"],
    outs: ["signal"],
    config: [{ name: "mix", type: "float", required: true, default: 0.5, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'modulation_amplitude',
    category: 'modulation',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal", "modulator"],
    outs: ["signal"],
    config: [{ name: "depth", type: "float", required: true, default: 0.5, min: 0, max: 2, unit: "ratio", realtime: true, structural: false }],
  },
  {
    name: 'modulation_frequency',
    category: 'modulation',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal", "modulator"],
    outs: ["signal"],
    config: [{ name: "depth", type: "float", required: true, default: 1, min: -4094, max: 4094, unit: "samples", realtime: true, structural: false }],
  },
  {
    name: 'modulation_phase',
    category: 'modulation',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal", "modulator"],
    outs: ["signal"],
    config: [{ name: "depth", type: "float", required: true, default: 1, min: 0, max: 4094, unit: "samples", realtime: true, structural: false }],
  },
  {
    name: 'modulation_phaser',
    category: 'modulation',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal", "modulator"],
    outs: ["signal"],
    config: [{ name: "center_frequency", type: "float", required: true, default: 900, min: 100, max: 4000, unit: "hz", scale: "logarithmic", realtime: true, smoothingMs: 10, structural: false }, { name: "depth", type: "float", required: true, default: 0.7, min: 0, max: 1, unit: "ratio", realtime: true, smoothingMs: 10, structural: false }, { name: "feedback", type: "float", required: true, default: 0.2, min: -0.85, max: 0.85, unit: "ratio", realtime: true, smoothingMs: 10, structural: false }],
  },
  {
    name: 'modulation_ring',
    category: 'modulation',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal", "modulator"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'modulation_scrub',
    category: 'modulation',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["buffer", "position"],
    outs: ["signal"],
    config: [{ name: "buffer_size", type: "int", required: true, default: 1024, min: 1, max: 192000, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'nonlinear_bitcrush',
    category: 'nonlinear',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "bit_depth", type: "float", required: true, default: 8, min: 1, max: 24, realtime: true, structural: false }],
  },
  {
    name: 'nonlinear_sample_hold',
    category: 'nonlinear',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "factor", type: "float", required: true, default: 4, min: 1, max: 1024, unit: "samples", realtime: true, structural: false }],
  },
  {
    name: 'nonlinear_waveshape',
    category: 'nonlinear',
    visibility: 'public',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "transfer_table", type: "buffer", required: true, default: "", realtime: false, structural: true }, { name: "table_size", type: "int", required: true, default: 0, min: 0, max: 65536, unit: "samples", realtime: false, structural: true }],
  },
  {
    name: 'src_antialias',
    category: 'src',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "cutoff", type: "float", required: true, default: 20000, min: 20, max: 20000, unit: "hz", scale: "logarithmic", realtime: true, structural: false }],
  },
  {
    name: 'src_antiimage',
    category: 'src',
    visibility: 'internal',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "cutoff", type: "float", required: true, default: 20000, min: 20, max: 20000, unit: "hz", scale: "logarithmic", realtime: true, structural: false }],
  },
  {
    name: 'src_convert_format',
    category: 'src',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "from_format", type: "enum", required: true, default: 0, realtime: false, structural: true, options: ["float32"], optionValues: [0] }, { name: "to_format", type: "enum", required: true, default: 0, realtime: false, structural: true, options: ["float32"], optionValues: [0] }],
  },
  {
    name: 'src_downsample',
    category: 'src',
    visibility: 'internal',
    dispatch: 'stream',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "factor", type: "int", required: true, default: 2, min: 2, max: 64, unit: "ratio", realtime: false, structural: true }],
  },
  {
    name: 'src_upsample',
    category: 'src',
    visibility: 'internal',
    dispatch: 'stream',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "factor", type: "int", required: true, default: 2, min: 2, max: 64, unit: "ratio", realtime: false, structural: true }],
  },
  {
    name: 'freq_quantize',
    category: 'freq',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'math_difference',
    category: 'math',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [],
  },
  {
    name: 'math_integrate',
    category: 'math',
    visibility: 'advanced',
    dispatch: 'process',
    ins: ["signal"],
    outs: ["signal"],
    config: [{ name: "leakage", type: "float", required: true, default: 1, min: 0, max: 1, unit: "ratio", realtime: true, structural: false }],
  },
];

export const PUBLIC_ATOM_CATALOG = ATOM_CATALOG.filter(atom => atom.visibility === 'public');
export const ADVANCED_ATOM_CATALOG = ATOM_CATALOG.filter(atom => atom.visibility === 'advanced');

export const ATOM_MAP = new Map<string, AtomDef>(ATOM_CATALOG.map(atom => [atom.name, atom]));
