/* Generated by codegen/generate_dsp_types_abi_snapshot.pl. */
#include <atom/dsp_types.h>

#include <stddef.h>
#include <stdio.h>

#define SNAPSHOT_ENUM(stream, enumerator) fprintf((stream), "enum,%s,,,,,%d\n", #enumerator, (int)(enumerator))
#define SNAPSHOT_TYPE(stream, type)       fprintf((stream), "type,%s,%zu,%zu,,,\n", #type, sizeof(type), _Alignof(type))
#define SNAPSHOT_FIELD(stream, type, field) \
    fprintf((stream), "field,%s,,,%s,%zu,\n", #type, #field, offsetof(type, field))

static FILE *open_output(int argc, char **argv) {
    if (argc == 1)
        return stdout;
    if (argc != 2)
        return NULL;
    return fopen(argv[1], "wb");
}

int main(int argc, char **argv) {
    FILE *output = open_output(argc, argv);
    if (!output) {
        fprintf(stderr, "usage: %s [OUTPUT_CSV]\n", argv[0]);
        return 2;
    }

    fputs("record,name,size,align,field,offset,value\n", output);

    SNAPSHOT_ENUM(output, WAVEFORM_SINE);
    SNAPSHOT_ENUM(output, WAVEFORM_SAW);
    SNAPSHOT_ENUM(output, WAVEFORM_SQUARE);
    SNAPSHOT_ENUM(output, WAVEFORM_TRIANGLE);
    SNAPSHOT_ENUM(output, WAVEFORM_NOISE_WHITE);
    SNAPSHOT_ENUM(output, WAVEFORM_NOISE_PINK);
    SNAPSHOT_ENUM(output, WAVEFORM_NOISE_BROWN);
    SNAPSHOT_ENUM(output, NORMALIZE_PEAK);
    SNAPSHOT_ENUM(output, NORMALIZE_RMS);
    SNAPSHOT_ENUM(output, INTERPOLATION_LINEAR);
    SNAPSHOT_ENUM(output, INTERPOLATION_CUBIC);
    SNAPSHOT_ENUM(output, INTERPOLATION_SINC);
    SNAPSHOT_ENUM(output, INTERPOLATION_LAGRANGE);
    SNAPSHOT_ENUM(output, WINDOW_HANN);
    SNAPSHOT_ENUM(output, WINDOW_HAMMING);
    SNAPSHOT_ENUM(output, WINDOW_BLACKMAN);
    SNAPSHOT_ENUM(output, WINDOW_RECTANGULAR);

    SNAPSHOT_TYPE(output, apg_buffer_t);
    SNAPSHOT_FIELD(output, apg_buffer_t, data);
    SNAPSHOT_FIELD(output, apg_buffer_t, capacity);

    SNAPSHOT_TYPE(output, apg_const_buffer_t);
    SNAPSHOT_FIELD(output, apg_const_buffer_t, data);
    SNAPSHOT_FIELD(output, apg_const_buffer_t, length);

    SNAPSHOT_TYPE(output, Signal);
    SNAPSHOT_FIELD(output, Signal, data);
    SNAPSHOT_FIELD(output, Signal, capacity);

    SNAPSHOT_TYPE(output, Spectrum);
    SNAPSHOT_FIELD(output, Spectrum, data);
    SNAPSHOT_FIELD(output, Spectrum, capacity);

    SNAPSHOT_TYPE(output, Buffer);
    SNAPSHOT_FIELD(output, Buffer, data);
    SNAPSHOT_FIELD(output, Buffer, capacity);

    SNAPSHOT_TYPE(output, atom_mono_t);
    SNAPSHOT_FIELD(output, atom_mono_t, signal);

    SNAPSHOT_TYPE(output, atom_pair_t);
    SNAPSHOT_FIELD(output, atom_pair_t, signal_a);
    SNAPSHOT_FIELD(output, atom_pair_t, signal_b);

    SNAPSHOT_TYPE(output, atom_stereo_t);
    SNAPSHOT_FIELD(output, atom_stereo_t, left);
    SNAPSHOT_FIELD(output, atom_stereo_t, right);

    SNAPSHOT_TYPE(output, atom_complex_t);
    SNAPSHOT_FIELD(output, atom_complex_t, real);
    SNAPSHOT_FIELD(output, atom_complex_t, imag);

    SNAPSHOT_TYPE(output, atom_ms_t);
    SNAPSHOT_FIELD(output, atom_ms_t, mid);
    SNAPSHOT_FIELD(output, atom_ms_t, side);

    SNAPSHOT_TYPE(output, atom_wet_dry_t);
    SNAPSHOT_FIELD(output, atom_wet_dry_t, dry);
    SNAPSHOT_FIELD(output, atom_wet_dry_t, wet);

    SNAPSHOT_TYPE(output, atom_div_t);
    SNAPSHOT_FIELD(output, atom_div_t, numerator);
    SNAPSHOT_FIELD(output, atom_div_t, denominator);

    SNAPSHOT_TYPE(output, amplitude_accumulate_out_t);
    SNAPSHOT_FIELD(output, amplitude_accumulate_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_accumulate_in_t);
    SNAPSHOT_FIELD(output, amplitude_accumulate_in_t, signal);

    SNAPSHOT_TYPE(output, amplitude_accumulate_params_t);
    SNAPSHOT_FIELD(output, amplitude_accumulate_params_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_accumulate_state_t);
    SNAPSHOT_FIELD(output, amplitude_accumulate_state_t, accumulator);

    SNAPSHOT_TYPE(output, amplitude_add_out_t);
    SNAPSHOT_FIELD(output, amplitude_add_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_add_in_t);
    SNAPSHOT_FIELD(output, amplitude_add_in_t, signal_a);
    SNAPSHOT_FIELD(output, amplitude_add_in_t, signal_b);

    SNAPSHOT_TYPE(output, amplitude_add_params_t);
    SNAPSHOT_FIELD(output, amplitude_add_params_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_add_state_t);
    SNAPSHOT_FIELD(output, amplitude_add_state_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_clip_hard_out_t);
    SNAPSHOT_FIELD(output, amplitude_clip_hard_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_clip_hard_in_t);
    SNAPSHOT_FIELD(output, amplitude_clip_hard_in_t, signal);

    SNAPSHOT_TYPE(output, amplitude_clip_hard_params_t);
    SNAPSHOT_FIELD(output, amplitude_clip_hard_params_t, threshold);

    SNAPSHOT_TYPE(output, amplitude_clip_hard_state_t);
    SNAPSHOT_FIELD(output, amplitude_clip_hard_state_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_clip_soft_out_t);
    SNAPSHOT_FIELD(output, amplitude_clip_soft_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_clip_soft_in_t);
    SNAPSHOT_FIELD(output, amplitude_clip_soft_in_t, signal);

    SNAPSHOT_TYPE(output, amplitude_clip_soft_params_t);
    SNAPSHOT_FIELD(output, amplitude_clip_soft_params_t, threshold);
    SNAPSHOT_FIELD(output, amplitude_clip_soft_params_t, curve);

    SNAPSHOT_TYPE(output, amplitude_clip_soft_state_t);
    SNAPSHOT_FIELD(output, amplitude_clip_soft_state_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_divide_out_t);
    SNAPSHOT_FIELD(output, amplitude_divide_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_divide_in_t);
    SNAPSHOT_FIELD(output, amplitude_divide_in_t, numerator);
    SNAPSHOT_FIELD(output, amplitude_divide_in_t, denominator);

    SNAPSHOT_TYPE(output, amplitude_divide_params_t);
    SNAPSHOT_FIELD(output, amplitude_divide_params_t, epsilon);

    SNAPSHOT_TYPE(output, amplitude_divide_state_t);
    SNAPSHOT_FIELD(output, amplitude_divide_state_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_latch_out_t);
    SNAPSHOT_FIELD(output, amplitude_latch_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_latch_in_t);
    SNAPSHOT_FIELD(output, amplitude_latch_in_t, signal);
    SNAPSHOT_FIELD(output, amplitude_latch_in_t, gate);

    SNAPSHOT_TYPE(output, amplitude_latch_params_t);
    SNAPSHOT_FIELD(output, amplitude_latch_params_t, threshold);

    SNAPSHOT_TYPE(output, amplitude_latch_state_t);
    SNAPSHOT_FIELD(output, amplitude_latch_state_t, latched_value);
    SNAPSHOT_FIELD(output, amplitude_latch_state_t, prev_gate);

    SNAPSHOT_TYPE(output, amplitude_multiply_out_t);
    SNAPSHOT_FIELD(output, amplitude_multiply_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_multiply_in_t);
    SNAPSHOT_FIELD(output, amplitude_multiply_in_t, signal_a);
    SNAPSHOT_FIELD(output, amplitude_multiply_in_t, signal_b);

    SNAPSHOT_TYPE(output, amplitude_multiply_params_t);
    SNAPSHOT_FIELD(output, amplitude_multiply_params_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_multiply_state_t);
    SNAPSHOT_FIELD(output, amplitude_multiply_state_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_normalize_out_t);
    SNAPSHOT_FIELD(output, amplitude_normalize_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_normalize_in_t);
    SNAPSHOT_FIELD(output, amplitude_normalize_in_t, signal);

    SNAPSHOT_TYPE(output, amplitude_normalize_params_t);
    SNAPSHOT_FIELD(output, amplitude_normalize_params_t, target_level);
    SNAPSHOT_FIELD(output, amplitude_normalize_params_t, mode);

    SNAPSHOT_TYPE(output, amplitude_normalize_state_t);
    SNAPSHOT_FIELD(output, amplitude_normalize_state_t, running_peak);

    SNAPSHOT_TYPE(output, amplitude_smooth_out_t);
    SNAPSHOT_FIELD(output, amplitude_smooth_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_smooth_in_t);
    SNAPSHOT_FIELD(output, amplitude_smooth_in_t, signal);

    SNAPSHOT_TYPE(output, amplitude_smooth_params_t);
    SNAPSHOT_FIELD(output, amplitude_smooth_params_t, attack);
    SNAPSHOT_FIELD(output, amplitude_smooth_params_t, release);

    SNAPSHOT_TYPE(output, amplitude_smooth_state_t);
    SNAPSHOT_FIELD(output, amplitude_smooth_state_t, prev_value);

    SNAPSHOT_TYPE(output, amplitude_subtract_out_t);
    SNAPSHOT_FIELD(output, amplitude_subtract_out_t, signal);

    SNAPSHOT_TYPE(output, amplitude_subtract_in_t);
    SNAPSHOT_FIELD(output, amplitude_subtract_in_t, signal_a);
    SNAPSHOT_FIELD(output, amplitude_subtract_in_t, signal_b);

    SNAPSHOT_TYPE(output, amplitude_subtract_params_t);
    SNAPSHOT_FIELD(output, amplitude_subtract_params_t, _reserved);

    SNAPSHOT_TYPE(output, amplitude_subtract_state_t);
    SNAPSHOT_FIELD(output, amplitude_subtract_state_t, _reserved);

    SNAPSHOT_TYPE(output, delay_fractional_out_t);
    SNAPSHOT_FIELD(output, delay_fractional_out_t, signal);

    SNAPSHOT_TYPE(output, delay_fractional_in_t);
    SNAPSHOT_FIELD(output, delay_fractional_in_t, signal);

    SNAPSHOT_TYPE(output, delay_fractional_params_t);
    SNAPSHOT_FIELD(output, delay_fractional_params_t, delay_samples);
    SNAPSHOT_FIELD(output, delay_fractional_params_t, interpolation);

    SNAPSHOT_TYPE(output, delay_fractional_state_t);
    SNAPSHOT_FIELD(output, delay_fractional_state_t, buffer);
    SNAPSHOT_FIELD(output, delay_fractional_state_t, buffer_len);
    SNAPSHOT_FIELD(output, delay_fractional_state_t, write_pos);

    SNAPSHOT_TYPE(output, delay_line_out_t);
    SNAPSHOT_FIELD(output, delay_line_out_t, signal);

    SNAPSHOT_TYPE(output, delay_line_in_t);
    SNAPSHOT_FIELD(output, delay_line_in_t, signal);

    SNAPSHOT_TYPE(output, delay_line_params_t);
    SNAPSHOT_FIELD(output, delay_line_params_t, length);

    SNAPSHOT_TYPE(output, delay_line_state_t);
    SNAPSHOT_FIELD(output, delay_line_state_t, buffer);
    SNAPSHOT_FIELD(output, delay_line_state_t, buffer_len);
    SNAPSHOT_FIELD(output, delay_line_state_t, write_pos);

    SNAPSHOT_TYPE(output, delay_tap_feedback_out_t);
    SNAPSHOT_FIELD(output, delay_tap_feedback_out_t, signal);

    SNAPSHOT_TYPE(output, delay_tap_feedback_in_t);
    SNAPSHOT_FIELD(output, delay_tap_feedback_in_t, buffer);
    SNAPSHOT_FIELD(output, delay_tap_feedback_in_t, tap_position);

    SNAPSHOT_TYPE(output, delay_tap_feedback_params_t);
    SNAPSHOT_FIELD(output, delay_tap_feedback_params_t, coefficient);

    SNAPSHOT_TYPE(output, delay_tap_feedback_state_t);
    SNAPSHOT_FIELD(output, delay_tap_feedback_state_t, _reserved);

    SNAPSHOT_TYPE(output, delay_tap_feedforward_out_t);
    SNAPSHOT_FIELD(output, delay_tap_feedforward_out_t, signal);

    SNAPSHOT_TYPE(output, delay_tap_feedforward_in_t);
    SNAPSHOT_FIELD(output, delay_tap_feedforward_in_t, buffer);
    SNAPSHOT_FIELD(output, delay_tap_feedforward_in_t, tap_position);

    SNAPSHOT_TYPE(output, delay_tap_feedforward_params_t);
    SNAPSHOT_FIELD(output, delay_tap_feedforward_params_t, coefficient);

    SNAPSHOT_TYPE(output, delay_tap_feedforward_state_t);
    SNAPSHOT_FIELD(output, delay_tap_feedforward_state_t, _reserved);

    SNAPSHOT_TYPE(output, delay_unit_out_t);
    SNAPSHOT_FIELD(output, delay_unit_out_t, signal);

    SNAPSHOT_TYPE(output, delay_unit_in_t);
    SNAPSHOT_FIELD(output, delay_unit_in_t, signal);

    SNAPSHOT_TYPE(output, delay_unit_params_t);
    SNAPSHOT_FIELD(output, delay_unit_params_t, _reserved);

    SNAPSHOT_TYPE(output, delay_unit_state_t);
    SNAPSHOT_FIELD(output, delay_unit_state_t, prev_sample);

    SNAPSHOT_TYPE(output, detect_autocorrelate_out_t);
    SNAPSHOT_FIELD(output, detect_autocorrelate_out_t, correlation);

    SNAPSHOT_TYPE(output, detect_autocorrelate_in_t);
    SNAPSHOT_FIELD(output, detect_autocorrelate_in_t, signal);

    SNAPSHOT_TYPE(output, detect_autocorrelate_params_t);
    SNAPSHOT_FIELD(output, detect_autocorrelate_params_t, max_lag);

    SNAPSHOT_TYPE(output, detect_autocorrelate_state_t);
    SNAPSHOT_FIELD(output, detect_autocorrelate_state_t, buffer);
    SNAPSHOT_FIELD(output, detect_autocorrelate_state_t, buffer_len);
    SNAPSHOT_FIELD(output, detect_autocorrelate_state_t, write_pos);

    SNAPSHOT_TYPE(output, detect_envelope_out_t);
    SNAPSHOT_FIELD(output, detect_envelope_out_t, envelope);

    SNAPSHOT_TYPE(output, detect_envelope_in_t);
    SNAPSHOT_FIELD(output, detect_envelope_in_t, signal);

    SNAPSHOT_TYPE(output, detect_envelope_params_t);
    SNAPSHOT_FIELD(output, detect_envelope_params_t, attack);
    SNAPSHOT_FIELD(output, detect_envelope_params_t, release);

    SNAPSHOT_TYPE(output, detect_envelope_state_t);
    SNAPSHOT_FIELD(output, detect_envelope_state_t, prev_envelope);

    SNAPSHOT_TYPE(output, detect_peak_out_t);
    SNAPSHOT_FIELD(output, detect_peak_out_t, level);

    SNAPSHOT_TYPE(output, detect_peak_in_t);
    SNAPSHOT_FIELD(output, detect_peak_in_t, signal);

    SNAPSHOT_TYPE(output, detect_peak_params_t);
    SNAPSHOT_FIELD(output, detect_peak_params_t, attack);
    SNAPSHOT_FIELD(output, detect_peak_params_t, release);

    SNAPSHOT_TYPE(output, detect_peak_state_t);
    SNAPSHOT_FIELD(output, detect_peak_state_t, prev_peak);

    SNAPSHOT_TYPE(output, detect_pitch_out_t);
    SNAPSHOT_FIELD(output, detect_pitch_out_t, pitch);

    SNAPSHOT_TYPE(output, detect_pitch_in_t);
    SNAPSHOT_FIELD(output, detect_pitch_in_t, signal);

    SNAPSHOT_TYPE(output, detect_pitch_params_t);
    SNAPSHOT_FIELD(output, detect_pitch_params_t, max_lag);

    SNAPSHOT_TYPE(output, detect_pitch_state_t);
    SNAPSHOT_FIELD(output, detect_pitch_state_t, buffer);
    SNAPSHOT_FIELD(output, detect_pitch_state_t, buffer_len);
    SNAPSHOT_FIELD(output, detect_pitch_state_t, write_pos);

    SNAPSHOT_TYPE(output, detect_rms_out_t);
    SNAPSHOT_FIELD(output, detect_rms_out_t, level);

    SNAPSHOT_TYPE(output, detect_rms_in_t);
    SNAPSHOT_FIELD(output, detect_rms_in_t, signal);

    SNAPSHOT_TYPE(output, detect_rms_params_t);
    SNAPSHOT_FIELD(output, detect_rms_params_t, window_size);

    SNAPSHOT_TYPE(output, detect_rms_state_t);
    SNAPSHOT_FIELD(output, detect_rms_state_t, buffer);
    SNAPSHOT_FIELD(output, detect_rms_state_t, buffer_len);
    SNAPSHOT_FIELD(output, detect_rms_state_t, write_pos);
    SNAPSHOT_FIELD(output, detect_rms_state_t, sum);

    SNAPSHOT_TYPE(output, detect_slope_out_t);
    SNAPSHOT_FIELD(output, detect_slope_out_t, slope);

    SNAPSHOT_TYPE(output, detect_slope_in_t);
    SNAPSHOT_FIELD(output, detect_slope_in_t, signal);

    SNAPSHOT_TYPE(output, detect_slope_params_t);
    SNAPSHOT_FIELD(output, detect_slope_params_t, _reserved);

    SNAPSHOT_TYPE(output, detect_slope_state_t);
    SNAPSHOT_FIELD(output, detect_slope_state_t, prev_sample);

    SNAPSHOT_TYPE(output, detect_threshold_out_t);
    SNAPSHOT_FIELD(output, detect_threshold_out_t, gate);

    SNAPSHOT_TYPE(output, detect_threshold_in_t);
    SNAPSHOT_FIELD(output, detect_threshold_in_t, signal);

    SNAPSHOT_TYPE(output, detect_threshold_params_t);
    SNAPSHOT_FIELD(output, detect_threshold_params_t, threshold);

    SNAPSHOT_TYPE(output, detect_threshold_state_t);
    SNAPSHOT_FIELD(output, detect_threshold_state_t, _reserved);

    SNAPSHOT_TYPE(output, detect_zero_crossing_out_t);
    SNAPSHOT_FIELD(output, detect_zero_crossing_out_t, trigger);

    SNAPSHOT_TYPE(output, detect_zero_crossing_in_t);
    SNAPSHOT_FIELD(output, detect_zero_crossing_in_t, signal);

    SNAPSHOT_TYPE(output, detect_zero_crossing_params_t);
    SNAPSHOT_FIELD(output, detect_zero_crossing_params_t, _reserved);

    SNAPSHOT_TYPE(output, detect_zero_crossing_state_t);
    SNAPSHOT_FIELD(output, detect_zero_crossing_state_t, prev_sample);

    SNAPSHOT_TYPE(output, filter_allpass_out_t);
    SNAPSHOT_FIELD(output, filter_allpass_out_t, signal);

    SNAPSHOT_TYPE(output, filter_allpass_in_t);
    SNAPSHOT_FIELD(output, filter_allpass_in_t, signal);

    SNAPSHOT_TYPE(output, filter_allpass_params_t);
    SNAPSHOT_FIELD(output, filter_allpass_params_t, delay_samples);
    SNAPSHOT_FIELD(output, filter_allpass_params_t, coefficient);

    SNAPSHOT_TYPE(output, filter_allpass_state_t);
    SNAPSHOT_FIELD(output, filter_allpass_state_t, buffer);
    SNAPSHOT_FIELD(output, filter_allpass_state_t, buffer_len);
    SNAPSHOT_FIELD(output, filter_allpass_state_t, write_pos);

    SNAPSHOT_TYPE(output, filter_biquad_out_t);
    SNAPSHOT_FIELD(output, filter_biquad_out_t, signal);

    SNAPSHOT_TYPE(output, filter_biquad_in_t);
    SNAPSHOT_FIELD(output, filter_biquad_in_t, signal);
    SNAPSHOT_FIELD(output, filter_biquad_in_t, cutoff);

    SNAPSHOT_TYPE(output, filter_biquad_params_t);
    SNAPSHOT_FIELD(output, filter_biquad_params_t, cutoff);
    SNAPSHOT_FIELD(output, filter_biquad_params_t, q);
    SNAPSHOT_FIELD(output, filter_biquad_params_t, mode);
    SNAPSHOT_FIELD(output, filter_biquad_params_t, smoothing_ms);

    SNAPSHOT_TYPE(output, filter_biquad_state_t);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, z1);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, z2);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_cutoff);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_q);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_b0);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_b1);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_b2);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_a1);
    SNAPSHOT_FIELD(output, filter_biquad_state_t, current_a2);

    SNAPSHOT_TYPE(output, filter_biquad_coefficients_out_t);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_out_t, signal);

    SNAPSHOT_TYPE(output, filter_biquad_coefficients_in_t);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_in_t, signal);

    SNAPSHOT_TYPE(output, filter_biquad_coefficients_params_t);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_params_t, b0);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_params_t, b1);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_params_t, b2);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_params_t, a1);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_params_t, a2);

    SNAPSHOT_TYPE(output, filter_biquad_coefficients_state_t);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_state_t, z1);
    SNAPSHOT_FIELD(output, filter_biquad_coefficients_state_t, z2);

    SNAPSHOT_TYPE(output, filter_comb_fb_out_t);
    SNAPSHOT_FIELD(output, filter_comb_fb_out_t, signal);

    SNAPSHOT_TYPE(output, filter_comb_fb_in_t);
    SNAPSHOT_FIELD(output, filter_comb_fb_in_t, signal);
    SNAPSHOT_FIELD(output, filter_comb_fb_in_t, delay);

    SNAPSHOT_TYPE(output, filter_comb_fb_params_t);
    SNAPSHOT_FIELD(output, filter_comb_fb_params_t, delay_samples);
    SNAPSHOT_FIELD(output, filter_comb_fb_params_t, coefficient);

    SNAPSHOT_TYPE(output, filter_comb_fb_state_t);
    SNAPSHOT_FIELD(output, filter_comb_fb_state_t, buffer);
    SNAPSHOT_FIELD(output, filter_comb_fb_state_t, buffer_len);
    SNAPSHOT_FIELD(output, filter_comb_fb_state_t, write_pos);

    SNAPSHOT_TYPE(output, filter_comb_ff_out_t);
    SNAPSHOT_FIELD(output, filter_comb_ff_out_t, signal);

    SNAPSHOT_TYPE(output, filter_comb_ff_in_t);
    SNAPSHOT_FIELD(output, filter_comb_ff_in_t, signal);

    SNAPSHOT_TYPE(output, filter_comb_ff_params_t);
    SNAPSHOT_FIELD(output, filter_comb_ff_params_t, delay_samples);
    SNAPSHOT_FIELD(output, filter_comb_ff_params_t, coefficient);

    SNAPSHOT_TYPE(output, filter_comb_ff_state_t);
    SNAPSHOT_FIELD(output, filter_comb_ff_state_t, buffer);
    SNAPSHOT_FIELD(output, filter_comb_ff_state_t, buffer_len);
    SNAPSHOT_FIELD(output, filter_comb_ff_state_t, write_pos);

    SNAPSHOT_TYPE(output, filter_dc_block_out_t);
    SNAPSHOT_FIELD(output, filter_dc_block_out_t, signal);

    SNAPSHOT_TYPE(output, filter_dc_block_in_t);
    SNAPSHOT_FIELD(output, filter_dc_block_in_t, signal);

    SNAPSHOT_TYPE(output, filter_dc_block_params_t);
    SNAPSHOT_FIELD(output, filter_dc_block_params_t, coefficient);

    SNAPSHOT_TYPE(output, filter_dc_block_state_t);
    SNAPSHOT_FIELD(output, filter_dc_block_state_t, prev_input);
    SNAPSHOT_FIELD(output, filter_dc_block_state_t, prev_output);

    SNAPSHOT_TYPE(output, filter_differentiate_out_t);
    SNAPSHOT_FIELD(output, filter_differentiate_out_t, signal);

    SNAPSHOT_TYPE(output, filter_differentiate_in_t);
    SNAPSHOT_FIELD(output, filter_differentiate_in_t, signal);

    SNAPSHOT_TYPE(output, filter_differentiate_params_t);
    SNAPSHOT_FIELD(output, filter_differentiate_params_t, _reserved);

    SNAPSHOT_TYPE(output, filter_differentiate_state_t);
    SNAPSHOT_FIELD(output, filter_differentiate_state_t, prev_sample);

    SNAPSHOT_TYPE(output, filter_fir_out_t);
    SNAPSHOT_FIELD(output, filter_fir_out_t, signal);

    SNAPSHOT_TYPE(output, filter_fir_in_t);
    SNAPSHOT_FIELD(output, filter_fir_in_t, signal);

    SNAPSHOT_TYPE(output, filter_fir_params_t);
    SNAPSHOT_FIELD(output, filter_fir_params_t, kernel);
    SNAPSHOT_FIELD(output, filter_fir_params_t, kernel_size);

    SNAPSHOT_TYPE(output, filter_fir_state_t);
    SNAPSHOT_FIELD(output, filter_fir_state_t, buffer);
    SNAPSHOT_FIELD(output, filter_fir_state_t, buffer_len);
    SNAPSHOT_FIELD(output, filter_fir_state_t, write_pos);

    SNAPSHOT_TYPE(output, filter_integrate_out_t);
    SNAPSHOT_FIELD(output, filter_integrate_out_t, signal);

    SNAPSHOT_TYPE(output, filter_integrate_in_t);
    SNAPSHOT_FIELD(output, filter_integrate_in_t, signal);

    SNAPSHOT_TYPE(output, filter_integrate_params_t);
    SNAPSHOT_FIELD(output, filter_integrate_params_t, _reserved);

    SNAPSHOT_TYPE(output, filter_integrate_state_t);
    SNAPSHOT_FIELD(output, filter_integrate_state_t, accumulator);

    SNAPSHOT_TYPE(output, freq_fft_out_t);
    SNAPSHOT_FIELD(output, freq_fft_out_t, real);
    SNAPSHOT_FIELD(output, freq_fft_out_t, imag);

    SNAPSHOT_TYPE(output, freq_fft_in_t);
    SNAPSHOT_FIELD(output, freq_fft_in_t, signal);

    SNAPSHOT_TYPE(output, freq_fft_params_t);
    SNAPSHOT_FIELD(output, freq_fft_params_t, block_size);

    SNAPSHOT_TYPE(output, freq_fft_state_t);
    SNAPSHOT_FIELD(output, freq_fft_state_t, workspace);
    SNAPSHOT_FIELD(output, freq_fft_state_t, buffer_len);

    SNAPSHOT_TYPE(output, freq_ifft_out_t);
    SNAPSHOT_FIELD(output, freq_ifft_out_t, signal);

    SNAPSHOT_TYPE(output, freq_ifft_in_t);
    SNAPSHOT_FIELD(output, freq_ifft_in_t, real);
    SNAPSHOT_FIELD(output, freq_ifft_in_t, imag);

    SNAPSHOT_TYPE(output, freq_ifft_params_t);
    SNAPSHOT_FIELD(output, freq_ifft_params_t, block_size);

    SNAPSHOT_TYPE(output, freq_ifft_state_t);
    SNAPSHOT_FIELD(output, freq_ifft_state_t, workspace);
    SNAPSHOT_FIELD(output, freq_ifft_state_t, buffer_len);

    SNAPSHOT_TYPE(output, freq_multiply_out_t);
    SNAPSHOT_FIELD(output, freq_multiply_out_t, real);
    SNAPSHOT_FIELD(output, freq_multiply_out_t, imag);

    SNAPSHOT_TYPE(output, freq_multiply_in_t);
    SNAPSHOT_FIELD(output, freq_multiply_in_t, real_a);
    SNAPSHOT_FIELD(output, freq_multiply_in_t, imag_a);
    SNAPSHOT_FIELD(output, freq_multiply_in_t, real_b);
    SNAPSHOT_FIELD(output, freq_multiply_in_t, imag_b);

    SNAPSHOT_TYPE(output, freq_multiply_params_t);
    SNAPSHOT_FIELD(output, freq_multiply_params_t, block_size);

    SNAPSHOT_TYPE(output, freq_multiply_state_t);
    SNAPSHOT_FIELD(output, freq_multiply_state_t, _reserved);

    SNAPSHOT_TYPE(output, freq_overlap_add_out_t);
    SNAPSHOT_FIELD(output, freq_overlap_add_out_t, signal);

    SNAPSHOT_TYPE(output, freq_overlap_add_in_t);
    SNAPSHOT_FIELD(output, freq_overlap_add_in_t, frame);

    SNAPSHOT_TYPE(output, freq_overlap_add_params_t);
    SNAPSHOT_FIELD(output, freq_overlap_add_params_t, block_size);
    SNAPSHOT_FIELD(output, freq_overlap_add_params_t, hop_size);

    SNAPSHOT_TYPE(output, freq_overlap_add_state_t);
    SNAPSHOT_FIELD(output, freq_overlap_add_state_t, buffer);
    SNAPSHOT_FIELD(output, freq_overlap_add_state_t, buffer_len);

    SNAPSHOT_TYPE(output, freq_overlap_save_out_t);
    SNAPSHOT_FIELD(output, freq_overlap_save_out_t, frame);

    SNAPSHOT_TYPE(output, freq_overlap_save_in_t);
    SNAPSHOT_FIELD(output, freq_overlap_save_in_t, signal);

    SNAPSHOT_TYPE(output, freq_overlap_save_params_t);
    SNAPSHOT_FIELD(output, freq_overlap_save_params_t, block_size);
    SNAPSHOT_FIELD(output, freq_overlap_save_params_t, hop_size);

    SNAPSHOT_TYPE(output, freq_overlap_save_state_t);
    SNAPSHOT_FIELD(output, freq_overlap_save_state_t, buffer);
    SNAPSHOT_FIELD(output, freq_overlap_save_state_t, buffer_len);
    SNAPSHOT_FIELD(output, freq_overlap_save_state_t, write_pos);

    SNAPSHOT_TYPE(output, freq_quantize_out_t);
    SNAPSHOT_FIELD(output, freq_quantize_out_t, signal);

    SNAPSHOT_TYPE(output, freq_quantize_in_t);
    SNAPSHOT_FIELD(output, freq_quantize_in_t, signal);

    SNAPSHOT_TYPE(output, freq_quantize_params_t);
    SNAPSHOT_FIELD(output, freq_quantize_params_t, unused);

    SNAPSHOT_TYPE(output, freq_quantize_state_t);
    SNAPSHOT_FIELD(output, freq_quantize_state_t, unused);

    SNAPSHOT_TYPE(output, freq_shift_out_t);
    SNAPSHOT_FIELD(output, freq_shift_out_t, signal);

    SNAPSHOT_TYPE(output, freq_shift_in_t);
    SNAPSHOT_FIELD(output, freq_shift_in_t, signal);
    SNAPSHOT_FIELD(output, freq_shift_in_t, pitch_shift);

    SNAPSHOT_TYPE(output, freq_shift_params_t);
    SNAPSHOT_FIELD(output, freq_shift_params_t, block_size);

    SNAPSHOT_TYPE(output, freq_shift_state_t);
    SNAPSHOT_FIELD(output, freq_shift_state_t, buffer);
    SNAPSHOT_FIELD(output, freq_shift_state_t, buffer_len);
    SNAPSHOT_FIELD(output, freq_shift_state_t, write_pos);
    SNAPSHOT_FIELD(output, freq_shift_state_t, read_ptr);

    SNAPSHOT_TYPE(output, freq_window_out_t);
    SNAPSHOT_FIELD(output, freq_window_out_t, signal);

    SNAPSHOT_TYPE(output, freq_window_in_t);
    SNAPSHOT_FIELD(output, freq_window_in_t, signal);

    SNAPSHOT_TYPE(output, freq_window_params_t);
    SNAPSHOT_FIELD(output, freq_window_params_t, window_type);
    SNAPSHOT_FIELD(output, freq_window_params_t, block_size);

    SNAPSHOT_TYPE(output, freq_window_state_t);
    SNAPSHOT_FIELD(output, freq_window_state_t, _reserved);

    SNAPSHOT_TYPE(output, generation_dc_out_t);
    SNAPSHOT_FIELD(output, generation_dc_out_t, signal);

    SNAPSHOT_TYPE(output, generation_dc_in_t);
    SNAPSHOT_FIELD(output, generation_dc_in_t, _reserved);

    SNAPSHOT_TYPE(output, generation_dc_params_t);
    SNAPSHOT_FIELD(output, generation_dc_params_t, value);

    SNAPSHOT_TYPE(output, generation_dc_state_t);
    SNAPSHOT_FIELD(output, generation_dc_state_t, _reserved);

    SNAPSHOT_TYPE(output, generation_envelope_out_t);
    SNAPSHOT_FIELD(output, generation_envelope_out_t, signal);

    SNAPSHOT_TYPE(output, generation_envelope_in_t);
    SNAPSHOT_FIELD(output, generation_envelope_in_t, gate);

    SNAPSHOT_TYPE(output, generation_envelope_params_t);
    SNAPSHOT_FIELD(output, generation_envelope_params_t, attack);
    SNAPSHOT_FIELD(output, generation_envelope_params_t, decay);
    SNAPSHOT_FIELD(output, generation_envelope_params_t, sustain);
    SNAPSHOT_FIELD(output, generation_envelope_params_t, release);

    SNAPSHOT_TYPE(output, generation_envelope_state_t);
    SNAPSHOT_FIELD(output, generation_envelope_state_t, current_level);
    SNAPSHOT_FIELD(output, generation_envelope_state_t, stage);

    SNAPSHOT_TYPE(output, generation_impulse_out_t);
    SNAPSHOT_FIELD(output, generation_impulse_out_t, signal);

    SNAPSHOT_TYPE(output, generation_impulse_in_t);
    SNAPSHOT_FIELD(output, generation_impulse_in_t, _reserved);

    SNAPSHOT_TYPE(output, generation_impulse_params_t);
    SNAPSHOT_FIELD(output, generation_impulse_params_t, interval);

    SNAPSHOT_TYPE(output, generation_impulse_state_t);
    SNAPSHOT_FIELD(output, generation_impulse_state_t, counter);

    SNAPSHOT_TYPE(output, generation_lfo_out_t);
    SNAPSHOT_FIELD(output, generation_lfo_out_t, signal);

    SNAPSHOT_TYPE(output, generation_lfo_in_t);
    SNAPSHOT_FIELD(output, generation_lfo_in_t, _reserved);

    SNAPSHOT_TYPE(output, generation_lfo_params_t);
    SNAPSHOT_FIELD(output, generation_lfo_params_t, frequency);
    SNAPSHOT_FIELD(output, generation_lfo_params_t, waveform);
    SNAPSHOT_FIELD(output, generation_lfo_params_t, phase_offset);

    SNAPSHOT_TYPE(output, generation_lfo_state_t);
    SNAPSHOT_FIELD(output, generation_lfo_state_t, phase);

    SNAPSHOT_TYPE(output, generation_noise_out_t);
    SNAPSHOT_FIELD(output, generation_noise_out_t, signal);

    SNAPSHOT_TYPE(output, generation_noise_in_t);
    SNAPSHOT_FIELD(output, generation_noise_in_t, _reserved);

    SNAPSHOT_TYPE(output, generation_noise_params_t);
    SNAPSHOT_FIELD(output, generation_noise_params_t, amplitude);
    SNAPSHOT_FIELD(output, generation_noise_params_t, color);

    SNAPSHOT_TYPE(output, generation_noise_state_t);
    SNAPSHOT_FIELD(output, generation_noise_state_t, seed);
    SNAPSHOT_FIELD(output, generation_noise_state_t, prev_value);

    SNAPSHOT_TYPE(output, generation_oscillator_out_t);
    SNAPSHOT_FIELD(output, generation_oscillator_out_t, signal);

    SNAPSHOT_TYPE(output, generation_oscillator_in_t);
    SNAPSHOT_FIELD(output, generation_oscillator_in_t, frequency);

    SNAPSHOT_TYPE(output, generation_oscillator_params_t);
    SNAPSHOT_FIELD(output, generation_oscillator_params_t, frequency);
    SNAPSHOT_FIELD(output, generation_oscillator_params_t, waveform);
    SNAPSHOT_FIELD(output, generation_oscillator_params_t, phase_offset);

    SNAPSHOT_TYPE(output, generation_oscillator_state_t);
    SNAPSHOT_FIELD(output, generation_oscillator_state_t, phase);

    SNAPSHOT_TYPE(output, interpolation_cubic_out_t);
    SNAPSHOT_FIELD(output, interpolation_cubic_out_t, signal);

    SNAPSHOT_TYPE(output, interpolation_cubic_in_t);
    SNAPSHOT_FIELD(output, interpolation_cubic_in_t, signal_n1);
    SNAPSHOT_FIELD(output, interpolation_cubic_in_t, signal_a);
    SNAPSHOT_FIELD(output, interpolation_cubic_in_t, signal_b);
    SNAPSHOT_FIELD(output, interpolation_cubic_in_t, signal_c);
    SNAPSHOT_FIELD(output, interpolation_cubic_in_t, t);

    SNAPSHOT_TYPE(output, interpolation_cubic_params_t);
    SNAPSHOT_FIELD(output, interpolation_cubic_params_t, _reserved);

    SNAPSHOT_TYPE(output, interpolation_cubic_state_t);
    SNAPSHOT_FIELD(output, interpolation_cubic_state_t, _reserved);

    SNAPSHOT_TYPE(output, interpolation_lagrange_out_t);
    SNAPSHOT_FIELD(output, interpolation_lagrange_out_t, signal);

    SNAPSHOT_TYPE(output, interpolation_lagrange_in_t);
    SNAPSHOT_FIELD(output, interpolation_lagrange_in_t, samples);
    SNAPSHOT_FIELD(output, interpolation_lagrange_in_t, t);

    SNAPSHOT_TYPE(output, interpolation_lagrange_params_t);
    SNAPSHOT_FIELD(output, interpolation_lagrange_params_t, order);

    SNAPSHOT_TYPE(output, interpolation_lagrange_state_t);
    SNAPSHOT_FIELD(output, interpolation_lagrange_state_t, _reserved);

    SNAPSHOT_TYPE(output, interpolation_linear_out_t);
    SNAPSHOT_FIELD(output, interpolation_linear_out_t, signal);

    SNAPSHOT_TYPE(output, interpolation_linear_in_t);
    SNAPSHOT_FIELD(output, interpolation_linear_in_t, signal_a);
    SNAPSHOT_FIELD(output, interpolation_linear_in_t, signal_b);
    SNAPSHOT_FIELD(output, interpolation_linear_in_t, t);

    SNAPSHOT_TYPE(output, interpolation_linear_params_t);
    SNAPSHOT_FIELD(output, interpolation_linear_params_t, _reserved);

    SNAPSHOT_TYPE(output, interpolation_linear_state_t);
    SNAPSHOT_FIELD(output, interpolation_linear_state_t, _reserved);

    SNAPSHOT_TYPE(output, interpolation_sinc_out_t);
    SNAPSHOT_FIELD(output, interpolation_sinc_out_t, signal);

    SNAPSHOT_TYPE(output, interpolation_sinc_in_t);
    SNAPSHOT_FIELD(output, interpolation_sinc_in_t, buffer);
    SNAPSHOT_FIELD(output, interpolation_sinc_in_t, position);

    SNAPSHOT_TYPE(output, interpolation_sinc_params_t);
    SNAPSHOT_FIELD(output, interpolation_sinc_params_t, num_taps);

    SNAPSHOT_TYPE(output, interpolation_sinc_state_t);
    SNAPSHOT_FIELD(output, interpolation_sinc_state_t, _reserved);

    SNAPSHOT_TYPE(output, math_difference_out_t);
    SNAPSHOT_FIELD(output, math_difference_out_t, signal);

    SNAPSHOT_TYPE(output, math_difference_in_t);
    SNAPSHOT_FIELD(output, math_difference_in_t, signal);

    SNAPSHOT_TYPE(output, math_difference_params_t);
    SNAPSHOT_FIELD(output, math_difference_params_t, _reserved);

    SNAPSHOT_TYPE(output, math_difference_state_t);
    SNAPSHOT_FIELD(output, math_difference_state_t, prev_sample);

    SNAPSHOT_TYPE(output, math_integrate_out_t);
    SNAPSHOT_FIELD(output, math_integrate_out_t, signal);

    SNAPSHOT_TYPE(output, math_integrate_in_t);
    SNAPSHOT_FIELD(output, math_integrate_in_t, signal);

    SNAPSHOT_TYPE(output, math_integrate_params_t);
    SNAPSHOT_FIELD(output, math_integrate_params_t, leakage);

    SNAPSHOT_TYPE(output, math_integrate_state_t);
    SNAPSHOT_FIELD(output, math_integrate_state_t, accumulator);

    SNAPSHOT_TYPE(output, mix_crossfade_out_t);
    SNAPSHOT_FIELD(output, mix_crossfade_out_t, signal);

    SNAPSHOT_TYPE(output, mix_crossfade_in_t);
    SNAPSHOT_FIELD(output, mix_crossfade_in_t, signal_a);
    SNAPSHOT_FIELD(output, mix_crossfade_in_t, signal_b);

    SNAPSHOT_TYPE(output, mix_crossfade_params_t);
    SNAPSHOT_FIELD(output, mix_crossfade_params_t, t);
    SNAPSHOT_FIELD(output, mix_crossfade_params_t, curve);

    SNAPSHOT_TYPE(output, mix_crossfade_state_t);
    SNAPSHOT_FIELD(output, mix_crossfade_state_t, _reserved);

    SNAPSHOT_TYPE(output, mix_decode_ms_out_t);
    SNAPSHOT_FIELD(output, mix_decode_ms_out_t, left);
    SNAPSHOT_FIELD(output, mix_decode_ms_out_t, right);

    SNAPSHOT_TYPE(output, mix_decode_ms_in_t);
    SNAPSHOT_FIELD(output, mix_decode_ms_in_t, mid);
    SNAPSHOT_FIELD(output, mix_decode_ms_in_t, side);

    SNAPSHOT_TYPE(output, mix_decode_ms_params_t);
    SNAPSHOT_FIELD(output, mix_decode_ms_params_t, _reserved);

    SNAPSHOT_TYPE(output, mix_decode_ms_state_t);
    SNAPSHOT_FIELD(output, mix_decode_ms_state_t, _reserved);

    SNAPSHOT_TYPE(output, mix_encode_ms_out_t);
    SNAPSHOT_FIELD(output, mix_encode_ms_out_t, mid);
    SNAPSHOT_FIELD(output, mix_encode_ms_out_t, side);

    SNAPSHOT_TYPE(output, mix_encode_ms_in_t);
    SNAPSHOT_FIELD(output, mix_encode_ms_in_t, left);
    SNAPSHOT_FIELD(output, mix_encode_ms_in_t, right);

    SNAPSHOT_TYPE(output, mix_encode_ms_params_t);
    SNAPSHOT_FIELD(output, mix_encode_ms_params_t, _reserved);

    SNAPSHOT_TYPE(output, mix_encode_ms_state_t);
    SNAPSHOT_FIELD(output, mix_encode_ms_state_t, _reserved);

    SNAPSHOT_TYPE(output, mix_matrix_out_t);
    SNAPSHOT_FIELD(output, mix_matrix_out_t, signals);

    SNAPSHOT_TYPE(output, mix_matrix_in_t);
    SNAPSHOT_FIELD(output, mix_matrix_in_t, signals);

    SNAPSHOT_TYPE(output, mix_matrix_params_t);
    SNAPSHOT_FIELD(output, mix_matrix_params_t, coefficients);
    SNAPSHOT_FIELD(output, mix_matrix_params_t, num_in);
    SNAPSHOT_FIELD(output, mix_matrix_params_t, num_out);

    SNAPSHOT_TYPE(output, mix_matrix_state_t);
    SNAPSHOT_FIELD(output, mix_matrix_state_t, _reserved);

    SNAPSHOT_TYPE(output, mix_pan_stereo_out_t);
    SNAPSHOT_FIELD(output, mix_pan_stereo_out_t, left);
    SNAPSHOT_FIELD(output, mix_pan_stereo_out_t, right);

    SNAPSHOT_TYPE(output, mix_pan_stereo_in_t);
    SNAPSHOT_FIELD(output, mix_pan_stereo_in_t, signal);

    SNAPSHOT_TYPE(output, mix_pan_stereo_params_t);
    SNAPSHOT_FIELD(output, mix_pan_stereo_params_t, position);

    SNAPSHOT_TYPE(output, mix_pan_stereo_state_t);
    SNAPSHOT_FIELD(output, mix_pan_stereo_state_t, _reserved);

    SNAPSHOT_TYPE(output, mix_wet_dry_out_t);
    SNAPSHOT_FIELD(output, mix_wet_dry_out_t, signal);

    SNAPSHOT_TYPE(output, mix_wet_dry_in_t);
    SNAPSHOT_FIELD(output, mix_wet_dry_in_t, dry);
    SNAPSHOT_FIELD(output, mix_wet_dry_in_t, wet);

    SNAPSHOT_TYPE(output, mix_wet_dry_params_t);
    SNAPSHOT_FIELD(output, mix_wet_dry_params_t, mix);

    SNAPSHOT_TYPE(output, mix_wet_dry_state_t);
    SNAPSHOT_FIELD(output, mix_wet_dry_state_t, _reserved);

    SNAPSHOT_TYPE(output, modulation_amplitude_out_t);
    SNAPSHOT_FIELD(output, modulation_amplitude_out_t, signal);

    SNAPSHOT_TYPE(output, modulation_amplitude_in_t);
    SNAPSHOT_FIELD(output, modulation_amplitude_in_t, signal);
    SNAPSHOT_FIELD(output, modulation_amplitude_in_t, modulator);

    SNAPSHOT_TYPE(output, modulation_amplitude_params_t);
    SNAPSHOT_FIELD(output, modulation_amplitude_params_t, depth);

    SNAPSHOT_TYPE(output, modulation_amplitude_state_t);
    SNAPSHOT_FIELD(output, modulation_amplitude_state_t, _reserved);

    SNAPSHOT_TYPE(output, modulation_frequency_out_t);
    SNAPSHOT_FIELD(output, modulation_frequency_out_t, signal);

    SNAPSHOT_TYPE(output, modulation_frequency_in_t);
    SNAPSHOT_FIELD(output, modulation_frequency_in_t, signal);
    SNAPSHOT_FIELD(output, modulation_frequency_in_t, modulator);

    SNAPSHOT_TYPE(output, modulation_frequency_params_t);
    SNAPSHOT_FIELD(output, modulation_frequency_params_t, depth);

    SNAPSHOT_TYPE(output, modulation_frequency_state_t);
    SNAPSHOT_FIELD(output, modulation_frequency_state_t, buffer);
    SNAPSHOT_FIELD(output, modulation_frequency_state_t, buffer_len);
    SNAPSHOT_FIELD(output, modulation_frequency_state_t, write_pos);
    SNAPSHOT_FIELD(output, modulation_frequency_state_t, current_delay);

    SNAPSHOT_TYPE(output, modulation_phase_out_t);
    SNAPSHOT_FIELD(output, modulation_phase_out_t, signal);

    SNAPSHOT_TYPE(output, modulation_phase_in_t);
    SNAPSHOT_FIELD(output, modulation_phase_in_t, signal);
    SNAPSHOT_FIELD(output, modulation_phase_in_t, modulator);

    SNAPSHOT_TYPE(output, modulation_phase_params_t);
    SNAPSHOT_FIELD(output, modulation_phase_params_t, depth);

    SNAPSHOT_TYPE(output, modulation_phase_state_t);
    SNAPSHOT_FIELD(output, modulation_phase_state_t, buffer);
    SNAPSHOT_FIELD(output, modulation_phase_state_t, buffer_len);
    SNAPSHOT_FIELD(output, modulation_phase_state_t, write_pos);

    SNAPSHOT_TYPE(output, modulation_phaser_out_t);
    SNAPSHOT_FIELD(output, modulation_phaser_out_t, signal);

    SNAPSHOT_TYPE(output, modulation_phaser_in_t);
    SNAPSHOT_FIELD(output, modulation_phaser_in_t, signal);
    SNAPSHOT_FIELD(output, modulation_phaser_in_t, modulator);

    SNAPSHOT_TYPE(output, modulation_phaser_params_t);
    SNAPSHOT_FIELD(output, modulation_phaser_params_t, center_frequency);
    SNAPSHOT_FIELD(output, modulation_phaser_params_t, depth);
    SNAPSHOT_FIELD(output, modulation_phaser_params_t, feedback);

    SNAPSHOT_TYPE(output, modulation_phaser_state_t);
    SNAPSHOT_FIELD(output, modulation_phaser_state_t, buffer);
    SNAPSHOT_FIELD(output, modulation_phaser_state_t, buffer_len);
    SNAPSHOT_FIELD(output, modulation_phaser_state_t, feedback_sample);

    SNAPSHOT_TYPE(output, modulation_ring_out_t);
    SNAPSHOT_FIELD(output, modulation_ring_out_t, signal);

    SNAPSHOT_TYPE(output, modulation_ring_in_t);
    SNAPSHOT_FIELD(output, modulation_ring_in_t, signal);
    SNAPSHOT_FIELD(output, modulation_ring_in_t, modulator);

    SNAPSHOT_TYPE(output, modulation_ring_params_t);
    SNAPSHOT_FIELD(output, modulation_ring_params_t, _reserved);

    SNAPSHOT_TYPE(output, modulation_ring_state_t);
    SNAPSHOT_FIELD(output, modulation_ring_state_t, _reserved);

    SNAPSHOT_TYPE(output, modulation_scrub_out_t);
    SNAPSHOT_FIELD(output, modulation_scrub_out_t, signal);

    SNAPSHOT_TYPE(output, modulation_scrub_in_t);
    SNAPSHOT_FIELD(output, modulation_scrub_in_t, buffer);
    SNAPSHOT_FIELD(output, modulation_scrub_in_t, position);

    SNAPSHOT_TYPE(output, modulation_scrub_params_t);
    SNAPSHOT_FIELD(output, modulation_scrub_params_t, buffer_size);

    SNAPSHOT_TYPE(output, modulation_scrub_state_t);
    SNAPSHOT_FIELD(output, modulation_scrub_state_t, _reserved);

    SNAPSHOT_TYPE(output, nonlinear_bitcrush_out_t);
    SNAPSHOT_FIELD(output, nonlinear_bitcrush_out_t, signal);

    SNAPSHOT_TYPE(output, nonlinear_bitcrush_in_t);
    SNAPSHOT_FIELD(output, nonlinear_bitcrush_in_t, signal);

    SNAPSHOT_TYPE(output, nonlinear_bitcrush_params_t);
    SNAPSHOT_FIELD(output, nonlinear_bitcrush_params_t, bit_depth);

    SNAPSHOT_TYPE(output, nonlinear_bitcrush_state_t);
    SNAPSHOT_FIELD(output, nonlinear_bitcrush_state_t, _reserved);

    SNAPSHOT_TYPE(output, nonlinear_sample_hold_out_t);
    SNAPSHOT_FIELD(output, nonlinear_sample_hold_out_t, signal);

    SNAPSHOT_TYPE(output, nonlinear_sample_hold_in_t);
    SNAPSHOT_FIELD(output, nonlinear_sample_hold_in_t, signal);

    SNAPSHOT_TYPE(output, nonlinear_sample_hold_params_t);
    SNAPSHOT_FIELD(output, nonlinear_sample_hold_params_t, factor);

    SNAPSHOT_TYPE(output, nonlinear_sample_hold_state_t);
    SNAPSHOT_FIELD(output, nonlinear_sample_hold_state_t, last_val);
    SNAPSHOT_FIELD(output, nonlinear_sample_hold_state_t, counter);

    SNAPSHOT_TYPE(output, nonlinear_waveshape_out_t);
    SNAPSHOT_FIELD(output, nonlinear_waveshape_out_t, signal);

    SNAPSHOT_TYPE(output, nonlinear_waveshape_in_t);
    SNAPSHOT_FIELD(output, nonlinear_waveshape_in_t, signal);

    SNAPSHOT_TYPE(output, nonlinear_waveshape_params_t);
    SNAPSHOT_FIELD(output, nonlinear_waveshape_params_t, transfer_table);
    SNAPSHOT_FIELD(output, nonlinear_waveshape_params_t, table_size);

    SNAPSHOT_TYPE(output, nonlinear_waveshape_state_t);
    SNAPSHOT_FIELD(output, nonlinear_waveshape_state_t, _reserved);

    SNAPSHOT_TYPE(output, src_antialias_out_t);
    SNAPSHOT_FIELD(output, src_antialias_out_t, signal);

    SNAPSHOT_TYPE(output, src_antialias_in_t);
    SNAPSHOT_FIELD(output, src_antialias_in_t, signal);

    SNAPSHOT_TYPE(output, src_antialias_params_t);
    SNAPSHOT_FIELD(output, src_antialias_params_t, cutoff);

    SNAPSHOT_TYPE(output, src_antialias_state_t);
    SNAPSHOT_FIELD(output, src_antialias_state_t, z1);
    SNAPSHOT_FIELD(output, src_antialias_state_t, z2);

    SNAPSHOT_TYPE(output, src_antiimage_out_t);
    SNAPSHOT_FIELD(output, src_antiimage_out_t, signal);

    SNAPSHOT_TYPE(output, src_antiimage_in_t);
    SNAPSHOT_FIELD(output, src_antiimage_in_t, signal);

    SNAPSHOT_TYPE(output, src_antiimage_params_t);
    SNAPSHOT_FIELD(output, src_antiimage_params_t, cutoff);

    SNAPSHOT_TYPE(output, src_antiimage_state_t);
    SNAPSHOT_FIELD(output, src_antiimage_state_t, z1);
    SNAPSHOT_FIELD(output, src_antiimage_state_t, z2);

    SNAPSHOT_TYPE(output, src_convert_format_out_t);
    SNAPSHOT_FIELD(output, src_convert_format_out_t, signal);

    SNAPSHOT_TYPE(output, src_convert_format_in_t);
    SNAPSHOT_FIELD(output, src_convert_format_in_t, signal);

    SNAPSHOT_TYPE(output, src_convert_format_params_t);
    SNAPSHOT_FIELD(output, src_convert_format_params_t, from_format);
    SNAPSHOT_FIELD(output, src_convert_format_params_t, to_format);

    SNAPSHOT_TYPE(output, src_convert_format_state_t);
    SNAPSHOT_FIELD(output, src_convert_format_state_t, _reserved);

    SNAPSHOT_TYPE(output, src_downsample_out_t);
    SNAPSHOT_FIELD(output, src_downsample_out_t, signal);

    SNAPSHOT_TYPE(output, src_downsample_in_t);
    SNAPSHOT_FIELD(output, src_downsample_in_t, signal);

    SNAPSHOT_TYPE(output, src_downsample_params_t);
    SNAPSHOT_FIELD(output, src_downsample_params_t, factor);

    SNAPSHOT_TYPE(output, src_downsample_state_t);
    SNAPSHOT_FIELD(output, src_downsample_state_t, phase);

    SNAPSHOT_TYPE(output, src_upsample_out_t);
    SNAPSHOT_FIELD(output, src_upsample_out_t, signal);

    SNAPSHOT_TYPE(output, src_upsample_in_t);
    SNAPSHOT_FIELD(output, src_upsample_in_t, signal);

    SNAPSHOT_TYPE(output, src_upsample_params_t);
    SNAPSHOT_FIELD(output, src_upsample_params_t, factor);

    SNAPSHOT_TYPE(output, src_upsample_state_t);
    SNAPSHOT_FIELD(output, src_upsample_state_t, phase);

    if (output != stdout && fclose(output) != 0)
        return 1;
    return 0;
}

#undef SNAPSHOT_FIELD
#undef SNAPSHOT_TYPE
#undef SNAPSHOT_ENUM
