#ifndef AUDIO_PLAYGROUND_APGCORE_BINDING_V2_H
#define AUDIO_PLAYGROUND_APGCORE_BINDING_V2_H

typedef enum {
    APG_BIND_SIGNAL,
    APG_BIND_PARAM,
    APG_BIND_LITERAL,
    APG_BIND_SIGNAL_ARRAY,
    APG_BIND_FLOAT_MATRIX,
} apg_v2_binding_kind_t;

#endif // AUDIO_PLAYGROUND_APGCORE_BINDING_V2_H
