#ifndef AUDIO_PLAYGROUND_ATOM_DEFINITIONS_H
#define AUDIO_PLAYGROUND_ATOM_DEFINITIONS_H

#include <atom/atom_capability.h>

#define APG_ATOM_FLAGS_COMMON       (APG_ATOM_RT_SAFE | APG_ATOM_NO_HEAP | APG_ATOM_BOUNDED_CPU)
#define APG_ATOM_FLAGS_PORTABLE     (APG_ATOM_FLAGS_COMMON | APG_ATOM_WASM_SAFE | APG_ATOM_M7_SAFE)
#define APG_ATOM_FLAGS_WASM         (APG_ATOM_FLAGS_COMMON | APG_ATOM_WASM_SAFE)
#define APG_ATOM_FLAGS_EXPERIMENTAL (APG_ATOM_EXPERIMENTAL | APG_ATOM_LEGACY)

#include <atom/generated/atom_definitions.generated.h>

#endif // AUDIO_PLAYGROUND_ATOM_DEFINITIONS_H
